events {}

http {
    upstream cv_parser {
        server cv-parser-a:8000;
        server cv-parser-b:8000;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://cv_parser;
            proxy_set_header Host $host;
        }
    }
}
